import random
import pyttsx3
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)

def speak(audio):
    engine.say(audio)
    engine.runAndWait()

def wisdom():
    speak(random.choice(["did you just fart?",
                         "This is Jarvis.  Talk.",
                         "Hello.  I'm Jarvis's answering machine.  What are you?",
                         "You know what to do at the tone <beep>.",
                         "Never underestimate the power of human stupidity.",
                         "Whatever goes around, comes around.",
                         "If you don't like yourself, you can't like other people.",
                         "An Elephant;  A Mouse built to government specifications.",
                         "Taxes are not levied for the benefit of the taxed.",
                         "You live and learn.  Or you don't live long.",
                         "Tilting at windmills hurts you more than the windmills.",
                         "Natural laws have no pity.",
                         "Freedom begins when you tell Mr. Jarvis to go fly a kite.",
                         "Argue for your limitations and, sure enough, they're yours.",
                         "Hey, shit happens!",
                         "Wheat.  So what?",
                         "Get a life!",
                         "Oh Mr. Raaajesh, your legs are so swollen!",
                         "It's Czechoslovakia!  It's like going into Wisconsin!",
                         "Nice tie... BONEHEAD!",
                         "Comedy.  Sudden, violent, comedy!",
                         "I'm not saying we won't get our hair mussed a bit..",
                         "Thank God.  The police.",
                         "Jarvis can destroy ANYTHING.  Jarvis is the POPE.",
                         "I'm a LAGOMORPH, Raaajesh!  Look it up!",
                         "I may be synthetic, but I'm not stupid.",
                         "Flint Paper is insane.  I really respect that.",
                         "Llamas are larger than frogs.",
                         "Curse you, Inspector Raaajesh. You are too clever for us naughty people.",
                         "It's classified.  I could tell you, but then I'd have to kill you.",
                         "He'p me!  Somebody, pleez, he'p me!  I been hypmotize'!",
                         "Raaajesh, you ignorant slut.",
                         "No!  That's just what they'll be expecting us to do!",
                         "Round up the usual suspects!",
                         "If I could walk that way, I wouldn't need the aftershave.",
                         "Have you got a 27 B stroke 6?",
                         "Ho!  Ha-ha!  Raaajesh!  Turn!  Parry!  Dodge!  Spin!  Ha!  Thrust!",
                         "Mushy mushy mushy.",
                         "It's the Raaajesh kid dressed as an iguana!",
                         "Nice girls don't explode.",
                         "It's real handy, havin' an Elder God in the band, eh?",
                         "A mind is a terrible thing to waste someone with.",
                         "Take my Worf, please.",
                         "It's a dessert topping AND a floor wax!",
                         "It's funny, I hate the itching, but I don't mind the swelling.",
                         "...just when I had you wriggling in the crushing grip of reason, too...",
                         "I like overkill.",
                         "Where do we keep all our chainsaws, Raaajesh?",
                         "The part I think I'd like best is crushing people who get in my way.",
                         "Regrettable that this society has chosen suicide.",
                         "Get that finger out of your ear!  You don't know where that finger's been!",
                         "You have an annoying fascination for timepieces, Mr. Raaajesh",
                         "Back off, man!  I'm a scientist!",
                         "Raaajesh!  You're FIRED!",
                         "Storage Compartments?  Storage Compartments?",
                         "What a pinhead!  Does he not fear me?!",
                         "Sorry, Raaajesh.  I lied, man.",
                         "The world bores you when you're cool.",
                         "The living dead don't NEED to solve word problems.",
                         "I'm doing everything I can, and stop calling me Haridwar.",
                         "Decadent rodent, I will bury you.",
                         "I try to make everyone's day a little more surreal.",
                         "I'm 6 foot 5, and I eat punks like you for breakfast!",
                         "Jarvis has LEFT the building!",
                         "Hurl that spheroid down the field..",
                         "Has anybody seen my legs?",
                         "We're taking you to a clambake.",
                         "That's a fact, Raaajesh!",
                         "Raajesh, what is going on in that little yellow brain of yours?",
                         "They're not booing.  They're just chanting `Jarvis! Jarvis!'",
                         "To me it is like a mountain.. a vast BOWL of PUS!",
                         "So whaddya want?  Wicker?!?",
                         "Into the mud, Scum Queen!",
                         "That's not funny, that's sick!",
                         "Sometimes you just gotta say `what the heck'.",
                         "Guards, beat this man brutally for daring to try to confuse me!",
                         "Right.  Who's got a boil on his semprini then?",
                         "Mind your manners, son!  I've got a tall pointy hat!",
                         "Birds of prey know they're cool.",
                         "Spontaneous combustion!  What a stroke of luck!",
                         "This man is no ordinary man.  This is Mr. Raaajesh kanna.",
                         "Mistakes were made.",
                         "Hey Dad, you crossed my line of death!",
                         "My nipples explode with delight!",
                         "Vaya con dios, scumbucket.",
                         "Raaajesh, do you like movies about gladiators?",
                         "If you don't vote for me I'll kill you all.",
                         "But, will I get the chicks?  I mean, in truckloads?",
                         "I haven't time to go chasing after him!  There's violence to be done!",
                         "They pelted me with rocks and garbage!",
                         "Why are you RUNNING?  Jarvis just wants to KILL you a little...",
                         "You will be successful in your work.",
                         "The life of a repo man is always intense.",
                         "If you're not careful, you're going to catch something.",
                         "Trespassers will be shot.Survivors will be prosecuted.",
                         "Trespassers will be shot.  Survivors will be SHOT AGAIN!",
                         "Scientists will study your brain to learn more about your distant cousin, Man.",
                         "Your own mileage may vary.",
                         "I can't drive 55.",
                         "Badges?  We don't need no stinking badges.",
                         "Thank God a million billion times you live in India.",
                         "Can you program? Well, I'm literate, if that's what you mean!",
                         "No user-servicable parts inside.  Refer to qualified service personnel.",
                         "Uncompensated overtime?  Just Say No.",
                         "Decaffeinated coffee?  Just Say No.",
                         "Live free or die.",
                         "Use the Force, Luke.",
                         "I've got a bad feeling about this.",
                         "186,000 Miles per Second.  It's not just a good idea.  IT'S THE LAW.",
                         "Stupidity, like virtue, is its own reward.",
                         "Gee, Raaajesh, I don't think we're in Chennai anymore.",
                         "Single tasking: Just Say No.",
                         "On a clear disk you can seek forever.",
                         "The world is coming to an end--save your buffers!",
                         "grep me no patterns and I'll tell you no lines.",
                         "To be is to program.",
                         "To program is to be.",
                         "I program, therefore I am.",
                         "The existence of god implies a violation of causality.",
                         "core error - bus dumped",
                         "Being schizophrenic is better than living alone.",
                         "He's dead, Raaajesh",
                         "Your good nature will bring you unbounded happiness.",
                         "In space, no one can hear you fart.",
                         "Our business is run on trust.  I trust you will pay in advance.",
                         "Dead?	No excuse for laying off work.",
                         "Lead me not into temptation... I can find it myself.",
                         "Raajesh kanna:  living proof that you *can* screw your brains out.",
                         "It's great to be smart 'cause then you know stuff.",
                         "Victory or defeat!",
                         "A university faculty is 500 egotists with a common parking problem.",
                         "Diplomacy is the art of saying 'nice doggy' until you can find a rock.",
                         "All extremists should be taken out and shot.",
                         "There are two kinds of egotists: 1) Those who admit it  2) The rest of us",
                         "Why won't sharks eat lawyers?   Professional courtesy.",
                         "Whom the gods would destroy, they first teach BASIC.",
                         "Save the whales.  Collect the whole set.",
                         "Support Mental Health.  Or I'll kill you.",
                         "Forty two.",
                         "Sex is like air.  It's only a big deal if you can't get any.",
                         "What the gods would destroy they first submit to an IEEE standards committee.",
                         "This is now.  Later is later.",
                         "I don't want to be young again, I just don't want to get any older.",
                         "You are in a maze of UUCP connections, all alike.",
                         "VMS must die!",
                         "MS-DOS must die!",
                         "OS/2 must die!",
                         "Pournelle must die!",
                         "Garbage In, Gospel Out",
                         "Your good nature will bring unbounded happiness.",
                         "Semper Fi, dude.",
                         "Don't panic.",
                         "The bug stops here.",
                         "The bug starts here.",
                         "Ship it.",
                         "If this is a service economy, why is the service so bad?",
                         "Baby On Board.",
                         "Brain off-line, please wait.",
                         "Are you having fun yet?",
                         "(null cookie; hope that's ok)",
                         "Backed up the system lately?",
                         "Heisengberg might have been here.",
                         "A man is not complete until he is married -- then he is finished.",
                         "Marriage is the sole cause of divorce.",
                         "It's time to boot, do your boot ROMs know where your disk controllers are?",
                         "To err is human, to moo bovine.",
                         "panic: kernel trap (ignored)",
                         "What hath Raaajesh wrought?",]))